import pluginReact from 'eslint-plugin-react';
import pluginReactHooks from 'eslint-plugin-react-hooks';

export default [
  {
    ignores: ['dist/**', 'node_modules/**', 'playwright-report/**', 'test-results/**', '.vite/**', 'vendor/**'],
  },
  {
    files: ['**/*.js', '**/*.jsx'],
    plugins: { react: pluginReact, 'react-hooks': pluginReactHooks },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        location: 'readonly',
        caches: 'readonly',
        self: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        EventSource: 'readonly',
        Image: 'readonly',
        FileReader: 'readonly',
        Blob: 'readonly',
        FormData: 'readonly',
        Promise: 'readonly',
        structuredClone: 'readonly',
        React: 'readonly',
        ReactDOM: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        performance: 'readonly',
        MessageChannel: 'readonly',
        CustomEvent: 'readonly',
        ResizeObserver: 'readonly',
        setImmediate: 'readonly',
        isInputPending: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        require: 'readonly',
        process: 'readonly',
        globalThis: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        IntersectionObserver: 'readonly',
        history: 'readonly',
        XMLSerializer: 'readonly',
        prompt: 'readonly',
      },
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    rules: {
      // React rules
      'react/jsx-uses-react': 'error',
      'react/jsx-uses-vars': 'error',

      'react/jsx-no-duplicate-props': 'error',
      'react/jsx-no-undef': 'error',
      'react/jsx-pascal-case': 'warn',
      'react/jsx-wrap-multilines': 'warn',
      'react/no-deprecated': 'warn',
      'react/no-direct-mutation-state': 'error',
      'react/no-unknown-property': 'warn',

      // React Hooks rules
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',

      // Best practices
      'no-unused-vars': ['warn', { args: 'none', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      'no-undef': 'error',
      'no-var': 'warn',
      'prefer-const': 'warn',
      'no-console': 'off',
      'no-debugger': 'warn',
      'no-alert': 'warn',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-shadow': 'warn',
      'no-use-before-define': ['warn', { functions: false, classes: false }],
      'no-duplicate-imports': 'warn',
      'no-return-assign': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-throw-literal': 'error',
      'no-unmodified-loop-condition': 'warn',
      'no-unused-expressions': 'warn',
      'no-useless-call': 'warn',
      'no-useless-concat': 'warn',
      'no-useless-return': 'warn',
      'no-void': 'error',
      'no-with': 'error',
      'radix': 'error',

      // ES6
      'arrow-body-style': ['warn', 'as-needed'],
      'arrow-spacing': 'warn',
      'no-duplicate-imports': 'warn',
      'no-useless-computed-key': 'warn',
      'no-useless-constructor': 'warn',
      'no-useless-rename': 'warn',
      'no-var': 'error',
      'object-shorthand': ['warn', 'always'],
      'prefer-arrow-callback': 'warn',
      'prefer-const': 'error',
      'prefer-destructuring': ['warn', { object: true, array: false }],
      'prefer-numeric-literals': 'warn',
      'prefer-rest-params': 'warn',
      'prefer-spread': 'warn',
      'prefer-template': 'warn',
      'rest-spread-spacing': 'warn',
      'template-curly-spacing': 'warn',
    },
    settings: {
      react: { version: 'detect' },
    },
  },
];
