#!/usr/bin/env python
"""Load BOM data from frontend data.js format into database"""

import asyncio
import os
import sys

# Add parent directory to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.db.base import Base
from app.db.session import get_session_maker, init_engine
from app.models.part import Part
from app.models.project import Project
from app.models.vendor import Vendor

# Extracted data from data.js
BOM_DATA = {
    "project": {
        "code": "ATL-MFR-A",
        "name": "Mainframe Assembly",
        "rev": "C",
        "version": "v3.2.0",
        "status": "Released",
        "owner": "E. Chen",
    },
    "rows": [
        {
            "pn": "ATL-MFR-A",
            "name": "Mainframe Assembly",
            "rev": "C",
            "qty": 1,
            "uom": "EA",
            "category": "Assembly",
            "vendor": "—",
            "cost": 4218.40,
            "lead": None,
            "origin": "—",
            "status": "Released",
            "assembly": True,
        },
        {
            "pn": "ATL-MFR-CHS",
            "name": "Chassis Subassembly",
            "rev": "B",
            "qty": 1,
            "uom": "EA",
            "category": "Assembly",
            "vendor": "—",
            "cost": 624.00,
            "lead": None,
            "origin": "—",
            "status": "Released",
            "assembly": True,
        },
        {
            "pn": "MEC-PL-040A",
            "name": "Side Panel, Anodized",
            "rev": "D",
            "qty": 2,
            "uom": "EA",
            "category": "Mechanical",
            "subCategory": "Enclosure",
            "vendor": "Protolabs",
            "manufacturer": "Blackbox Internal",
            "cost": 46.20,
            "lead": 7,
            "origin": "US",
            "status": "Released",
            "material": "Aluminum 6061-T6",
            "weight": 320,
            "dimensions": "200 × 120 × 3 mm",
            "tags": "enclosure,custom",
            "compliance": "RoHS",
            "freight": 4.20,
            "tax": 8.40,
            "landedCost": 58.80,
            "countryHistory": [{"country": "US", "date": "2025-11", "reason": "Initial sourcing"}],
            "vendorPrices": [{"vendor": "Protolabs", "cost": 46.20, "lead": 7, "moq": 1}],
            "cadUrl": "cad/ATLAS/Mainframe/MEC-PL-040A.step",
        },
        {
            "pn": "MEC-PL-041A",
            "name": "Top Plate, Vented",
            "rev": "B",
            "qty": 1,
            "uom": "EA",
            "category": "Mechanical",
            "subCategory": "Enclosure",
            "vendor": "Xometry",
            "manufacturer": "Blackbox Internal",
            "cost": 58.90,
            "lead": 9,
            "origin": "US",
            "status": "Released",
            "material": "Aluminum 6061-T6",
            "weight": 245,
            "dimensions": "200 × 120 × 2.5 mm",
            "tags": "enclosure,vented",
            "compliance": "RoHS",
            "freight": 5.20,
            "tax": 10.80,
            "landedCost": 74.90,
            "countryHistory": [{"country": "US", "date": "2025-10", "reason": "Initial sourcing"}],
            "vendorPrices": [{"vendor": "Xometry", "cost": 58.90, "lead": 9, "moq": 1}],
            "cadUrl": "cad/ATLAS/Mainframe/MEC-PL-041A.step",
        },
        {
            "pn": "MEC-BR-012",
            "name": "Mounting Bracket, L-form",
            "rev": "A",
            "qty": 4,
            "uom": "EA",
            "category": "Mechanical",
            "subCategory": "Bracket",
            "vendor": "Protolabs",
            "manufacturer": "Blackbox Internal",
            "cost": 8.40,
            "lead": 7,
            "origin": "US",
            "status": "Released",
            "material": "Steel A2-70",
            "weight": 45,
            "dimensions": "40 × 30 × 4 mm",
            "vendorPrices": [{"vendor": "Protolabs", "cost": 8.40, "lead": 7, "moq": 1}],
            "cadUrl": "cad/ATLAS/Mainframe/MEC-BR-012.step",
        },
        {
            "pn": "HW-FAS-M3-08",
            "name": "Screw, M3×8 Socket Head",
            "rev": "—",
            "qty": 24,
            "uom": "EA",
            "category": "Hardware",
            "subCategory": "Fastener",
            "vendor": "McMaster",
            "manufacturer": "McMaster-Carr",
            "cost": 0.08,
            "lead": 2,
            "origin": "CN",
            "status": "Released",
            "barcode": "8901234567890",
            "material": "Stainless Steel A2",
            "weight": 1.2,
            "dimensions": "M3 × 8 mm",
            "vendorPrices": [{"vendor": "McMaster", "cost": 0.08, "lead": 2, "moq": 100}],
        },
        {
            "pn": "HW-NUT-M3",
            "name": "Nut, M3 Locking",
            "rev": "—",
            "qty": 24,
            "uom": "EA",
            "category": "Hardware",
            "subCategory": "Fastener",
            "vendor": "McMaster",
            "manufacturer": "McMaster-Carr",
            "cost": 0.04,
            "lead": 2,
            "origin": "CN",
            "status": "Released",
            "barcode": "8901234567891",
            "material": "Stainless Steel A2",
            "weight": 0.6,
            "dimensions": "M3 × 2.4 mm",
        },
        {
            "pn": "EL-PSU-240W",
            "name": "Power Supply, 240W ATX",
            "rev": "E",
            "qty": 1,
            "uom": "EA",
            "category": "Electrical",
            "subCategory": "Power Supply",
            "vendor": "Mean Well",
            "manufacturer": "Mean Well",
            "cost": 84.00,
            "lead": 21,
            "origin": "TW",
            "status": "Released",
            "material": "Aluminum/PCB",
            "weight": 680,
            "dimensions": "150 × 86 × 65 mm",
            "tags": "power,psu,critical",
            "compliance": "RoHS,CE,UL",
            "freight": 12.00,
            "tax": 15.40,
            "landedCost": 111.40,
            "countryHistory": [
                {"country": "TW", "date": "2025-06", "reason": "Initial"},
                {"country": "TW", "date": "2026-01", "reason": "Price renegotiation"},
            ],
            "vendorPrices": [
                {"vendor": "Mean Well", "cost": 84.00, "lead": 21, "moq": 50},
                {"vendor": "Delta Electronics", "cost": 92.50, "lead": 28, "moq": 100},
            ],
        },
        {
            "pn": "EL-BAT-LI-18650",
            "name": "Cell, Li-Ion 18650 3500mAh",
            "rev": "B",
            "qty": 12,
            "uom": "EA",
            "category": "Electrical",
            "subCategory": "Battery",
            "vendor": "Panasonic",
            "manufacturer": "Panasonic",
            "cost": 8.20,
            "lead": 28,
            "origin": "JP",
            "status": "Review",
            "barcode": "4988600248173",
            "material": "Lithium-Ion",
            "weight": 47,
            "dimensions": "18 × 65 mm (cylindrical)",
            "tags": "battery,cell,long-lead",
            "compliance": "RoHS,UN38.3",
            "freight": 0.60,
            "tax": 1.50,
            "landedCost": 10.30,
            "countryHistory": [{"country": "JP", "date": "2025-07", "reason": "Initial"}],
            "vendorPrices": [
                {"vendor": "Panasonic", "cost": 8.20, "lead": 28, "moq": 100},
                {"vendor": "Samsung SDI", "cost": 7.80, "lead": 35, "moq": 200},
            ],
        },
        {
            "pn": "EL-MCU-STM32H7",
            "name": "MCU Module, STM32H743",
            "rev": "B",
            "qty": 1,
            "uom": "EA",
            "category": "Electrical",
            "subCategory": "IC",
            "vendor": "STMicro",
            "manufacturer": "STMicroelectronics",
            "cost": 18.40,
            "lead": 42,
            "origin": "FR",
            "status": "Released",
            "barcode": "8901234567892",
            "material": "Silicon/FR4",
            "weight": 5,
            "dimensions": "14 × 14 mm (LQFP-100)",
            "tags": "mcu,active,long-lead",
            "compliance": "RoHS,REACH",
            "freight": 1.20,
            "tax": 3.40,
            "landedCost": 23.00,
            "countryHistory": [
                {"country": "FR", "date": "2025-03", "reason": "Initial"},
                {"country": "FR", "date": "2026-02", "reason": "Rev B upgrade"},
            ],
            "vendorPrices": [
                {"vendor": "STMicro", "cost": 18.40, "lead": 42, "moq": 250},
                {"vendor": "Mouser", "cost": 19.50, "lead": 14, "moq": 1},
            ],
        },
        {
            "pn": "EL-PCB-MAIN-R3",
            "name": "Main PCB, R3 (4-layer)",
            "rev": "C",
            "qty": 1,
            "uom": "EA",
            "category": "Electrical",
            "subCategory": "PCB",
            "vendor": "JLCPCB",
            "manufacturer": "JLCPCB",
            "cost": 62.00,
            "lead": 14,
            "origin": "CN",
            "status": "Review",
            "material": "FR4",
            "weight": 85,
            "dimensions": "120 × 80 × 1.6 mm",
            "tags": "pcb,main,4-layer",
            "compliance": "RoHS,UL",
            "freight": 4.20,
            "tax": 11.40,
            "landedCost": 77.60,
            "countryHistory": [
                {"country": "CN", "date": "2026-01", "reason": "Initial proto"},
                {"country": "CN", "date": "2026-04", "reason": "R3 revision"},
            ],
            "vendorPrices": [
                {"vendor": "JLCPCB", "cost": 62.00, "lead": 14, "moq": 5},
                {"vendor": "PCBWay", "cost": 58.00, "lead": 18, "moq": 10},
            ],
        },
        {
            "pn": "EL-MEM-DDR4-8G",
            "name": "Memory, DDR4 8GB SODIMM",
            "rev": "A",
            "qty": 2,
            "uom": "EA",
            "category": "Electrical",
            "subCategory": "Memory",
            "vendor": "Crucial",
            "manufacturer": "Crucial",
            "cost": 32.50,
            "lead": 10,
            "origin": "US",
            "status": "Released",
            "barcode": "4988600248174",
            "material": "Silicon/FR4",
            "weight": 8,
            "dimensions": "67.6 × 30 × 3.7 mm",
            "tags": "memory,ddr4,sodimm",
            "compliance": "RoHS",
            "freight": 2.40,
            "tax": 6.00,
            "landedCost": 40.90,
            "vendorPrices": [
                {"vendor": "Crucial", "cost": 32.50, "lead": 10, "moq": 1},
                {"vendor": "Kingston", "cost": 34.00, "lead": 7, "moq": 1},
            ],
        },
        {
            "pn": "EL-CAM-IMX477",
            "name": "Image Sensor Module, IMX477",
            "rev": "B",
            "qty": 1,
            "uom": "EA",
            "category": "Optical",
            "subCategory": "Camera",
            "vendor": "Arducam",
            "manufacturer": "Sony",
            "cost": 48.00,
            "lead": 18,
            "origin": "CN",
            "status": "Released",
            "barcode": "4988600248175",
            "material": "Glass/Silicon/FR4",
            "weight": 12,
            "dimensions": "25 × 25 × 8 mm",
            "tags": "camera,sensor,optical",
            "compliance": "RoHS",
            "freight": 3.60,
            "tax": 8.80,
            "landedCost": 60.40,
            "countryHistory": [{"country": "CN", "date": "2025-09", "reason": "Initial"}],
            "vendorPrices": [
                {"vendor": "Arducam", "cost": 48.00, "lead": 18, "moq": 5},
                {"vendor": "Raspberry Pi", "cost": 52.00, "lead": 14, "moq": 10},
            ],
        },
        {
            "pn": "OPT-LNS-25MM",
            "name": "Lens Assembly, 25mm f/1.8",
            "rev": "A",
            "qty": 1,
            "uom": "EA",
            "category": "Optical",
            "subCategory": "Lens",
            "vendor": "Edmund Optics",
            "manufacturer": "Edmund Optics",
            "cost": 189.00,
            "lead": 21,
            "origin": "US",
            "status": "Approved",
            "barcode": "8901234567893",
            "material": "Glass/Aluminum",
            "weight": 45,
            "dimensions": "Ø30 × 28 mm",
            "tags": "lens,optical,critical",
            "compliance": "RoHS",
            "freight": 14.20,
            "tax": 34.80,
            "landedCost": 238.00,
            "countryHistory": [{"country": "US", "date": "2025-12", "reason": "Initial"}],
            "vendorPrices": [
                {"vendor": "Edmund Optics", "cost": 189.00, "lead": 21, "moq": 1},
                {"vendor": "Thorlabs", "cost": 175.00, "lead": 14, "moq": 1},
            ],
        },
        {
            "pn": "EL-FAN-92",
            "name": "Fan, 92mm PWM",
            "rev": "C",
            "qty": 2,
            "uom": "EA",
            "category": "Electrical",
            "subCategory": "Fan",
            "vendor": "Noctua",
            "manufacturer": "Noctua",
            "cost": 28.00,
            "lead": 14,
            "origin": "AT",
            "status": "Released",
            "material": "Plastic/Steel",
            "weight": 92,
            "dimensions": "92 × 92 × 25 mm",
            "tags": "fan,cooling,active",
            "compliance": "RoHS,CE",
            "freight": 2.10,
            "tax": 5.20,
            "landedCost": 35.30,
            "vendorPrices": [
                {"vendor": "Noctua", "cost": 28.00, "lead": 14, "moq": 10},
                {"vendor": "Arctic", "cost": 18.00, "lead": 10, "moq": 20},
            ],
        },
        {
            "pn": "EL-BMS-12S",
            "name": "BMS Board, 12S 60A",
            "rev": "A",
            "qty": 1,
            "uom": "EA",
            "category": "Electrical",
            "subCategory": "BMS",
            "vendor": "Daly",
            "manufacturer": "Daly",
            "cost": 64.00,
            "lead": 35,
            "origin": "CN",
            "status": "Released",
            "material": "FR4/Components",
            "weight": 32,
            "dimensions": "100 × 60 × 12 mm",
            "tags": "bms,battery,critical",
            "compliance": "RoHS,CE",
            "freight": 4.80,
            "tax": 11.70,
            "landedCost": 80.50,
            "countryHistory": [{"country": "CN", "date": "2025-08", "reason": "Initial"}],
            "vendorPrices": [
                {"vendor": "Daly", "cost": 64.00, "lead": 35, "moq": 10},
                {"vendor": "JK BMS", "cost": 72.00, "lead": 21, "moq": 25},
            ],
        },
    ],
    "vendors": [
        {
            "name": "Mean Well",
            "country": "TW",
            "leadTime": 21,
            "reliabilityRating": 4.6,
            "moq": 50,
            "terms": "Net 30",
        },
        {
            "name": "Protolabs",
            "country": "US",
            "leadTime": 7,
            "reliabilityRating": 4.4,
            "moq": 1,
            "terms": "Net 15",
        },
        {
            "name": "McMaster",
            "country": "US",
            "leadTime": 2,
            "reliabilityRating": 4.9,
            "moq": 1,
            "terms": "Net 30",
        },
        {
            "name": "JLCPCB",
            "country": "CN",
            "leadTime": 14,
            "reliabilityRating": 4.2,
            "moq": 5,
            "terms": "Prepaid",
        },
        {
            "name": "Edmund Optics",
            "country": "US",
            "leadTime": 21,
            "reliabilityRating": 4.5,
            "moq": 1,
            "terms": "Net 30",
        },
        {
            "name": "STMicro",
            "country": "FR",
            "leadTime": 42,
            "reliabilityRating": 4.0,
            "moq": 250,
            "terms": "Net 60",
        },
        {
            "name": "Daly",
            "country": "CN",
            "leadTime": 35,
            "reliabilityRating": 3.7,
            "moq": 10,
            "terms": "Prepaid",
        },
        {
            "name": "Panasonic",
            "country": "JP",
            "leadTime": 28,
            "reliabilityRating": 4.7,
            "moq": 100,
            "terms": "Net 45",
        },
        {
            "name": "Noctua",
            "country": "AT",
            "leadTime": 14,
            "reliabilityRating": 4.8,
            "moq": 10,
            "terms": "Net 30",
        },
        {
            "name": "Xometry",
            "country": "US",
            "leadTime": 9,
            "reliabilityRating": 4.3,
            "moq": 1,
            "terms": "Net 30",
        },
        {
            "name": "Crucial",
            "country": "US",
            "leadTime": 10,
            "reliabilityRating": 4.6,
            "moq": 1,
            "terms": "Net 15",
        },
        {
            "name": "Arducam",
            "country": "CN",
            "leadTime": 18,
            "reliabilityRating": 4.1,
            "moq": 5,
            "terms": "Prepaid",
        },
        {
            "name": "Molex",
            "country": "US",
            "leadTime": 14,
            "reliabilityRating": 4.5,
            "moq": 100,
            "terms": "Net 30",
        },
        {
            "name": "Amphenol",
            "country": "US",
            "leadTime": 9,
            "reliabilityRating": 4.6,
            "moq": 50,
            "terms": "Net 30",
        },
    ],
}


async def load_bom_data():
    """Load BOM data into database"""
    # Create tables
    engine = await init_engine()
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    # Create session
    async with (await get_session_maker())() as session:
        from sqlalchemy import func, select

        # Check if data already exists
        result = await session.execute(select(func.count()).select_from(Part))
        count = result.scalar()

        if count > 0:
            print(f"Database already has {count} parts. Skipping load.")
            return

        # Load parts
        for part_data in BOM_DATA["rows"]:
            # Convert list fields to JSON strings if needed
            part = Part(**part_data)
            session.add(part)

        # Load vendors
        for vendor_data in BOM_DATA["vendors"]:
            vendor = Vendor(**vendor_data)
            session.add(vendor)

        # Load project
        project = Project(**BOM_DATA["project"])
        session.add(project)

        # Commit
        await session.commit()

        print(f"Loaded {len(BOM_DATA['rows'])} parts")
        print(f"Loaded {len(BOM_DATA['vendors'])} vendors")
        print("Loaded 1 project")


if __name__ == "__main__":
    asyncio.run(load_bom_data())
