"""Point-in-Time Recovery (PITR) for PostgreSQL.
Generates recovery.signal and a dedicated recovery config file
to replay WAL archives up to a target timestamp or transaction ID.

Uses a separate recovery.conf (not postgresql.auto.conf) to avoid
corrupting existing PostgreSQL settings. Supports WAL archive cleanup.

Usage:
  python pitr_restore.py --target-time "2026-06-17 12:00:00 UTC"
  python pitr_restore.py --target-xid 123456789
  python pitr_restore.py --cleanup-wal --keep-days 7
"""

import argparse
import os
import sys
from datetime import UTC, datetime, timedelta
from pathlib import Path

WAL_ARCHIVE_DIR = "/var/lib/postgresql/wal_archive"
PG_DATA_DIR = "/var/lib/postgresql/data"
RESTORE_COMMAND = "cp /var/lib/postgresql/wal_archive/%f %p"


def generate_recovery_conf(target_time: str = None, target_xid: str = None) -> str:
    lines = [
        "# PostgreSQL Point-in-Time Recovery configuration",
        "# Generated by Blackbox BOM PITR restore script",
        f"# {datetime.now(UTC).isoformat()}",
        "",
        "restore_command = '" + RESTORE_COMMAND + "'",
    ]
    if target_time:
        lines.append(f"recovery_target_time = '{target_time}'")
    if target_xid:
        lines.append(f"recovery_target_xid = '{target_xid}'")
    lines.append("recovery_target_action = 'promote'")
    lines.append("")
    return "\n".join(lines)


def generate_recovery_signal() -> str:
    return ""


def cleanup_wal_archive(archive_dir: str, keep_days: int = 7, dry_run: bool = False) -> dict:
    """Remove WAL archive files older than keep_days."""
    archive = Path(archive_dir)
    if not archive.is_dir():
        return {
            "status": "error",
            "message": f"WAL archive directory does not exist: {archive_dir}",
        }

    cutoff = datetime.now() - timedelta(days=keep_days)
    removed = []
    total_size = 0

    for f in archive.iterdir():
        if not f.is_file():
            continue
        mtime = datetime.fromtimestamp(f.stat().st_mtime)
        if mtime < cutoff:
            total_size += f.stat().st_size
            if not dry_run:
                f.unlink()
            removed.append(str(f.name))

    return {
        "status": "ok",
        "removed_count": len(removed),
        "removed_files": removed,
        "freed_bytes": total_size,
        "dry_run": dry_run,
    }


def write_restore_files(
    target_time: str = None,
    target_xid: str = None,
    data_dir: str = PG_DATA_DIR,
    dry_run: bool = False,
) -> dict:
    conf = generate_recovery_conf(target_time, target_xid)
    # Use a dedicated recovery config file instead of appending to postgresql.auto.conf
    recovery_conf_path = os.path.join(data_dir, "blackbox_recovery.conf")
    recovery_signal_path = os.path.join(data_dir, "recovery.signal")

    if not os.path.isdir(data_dir):
        return {
            "status": "error",
            "message": f"Data directory does not exist: {data_dir}",
        }

    wal_archive = Path(WAL_ARCHIVE_DIR)
    if not wal_archive.is_dir():
        return {
            "status": "error",
            "message": f"WAL archive directory does not exist: {WAL_ARCHIVE_DIR}",
        }

    wal_count = (
        len([f for f in wal_archive.iterdir() if f.is_file()]) if wal_archive.is_dir() else 0
    )

    if dry_run:
        return {
            "status": "dry_run",
            "message": "PITR restore configuration generated (dry run)",
            "recovery_conf": conf,
            "recovery_conf_path": recovery_conf_path,
            "recovery_signal_path": recovery_signal_path,
            "wal_archive": WAL_ARCHIVE_DIR,
            "wal_file_count": wal_count,
            "target_time": target_time,
            "target_xid": target_xid,
        }

    try:
        with open(recovery_signal_path, "w") as f:
            f.write("")
        os.chmod(recovery_signal_path, 0o600)

        # Write to separate recovery config file (NOT postgresql.auto.conf)
        with open(recovery_conf_path, "w") as f:
            f.write(conf)
        os.chmod(recovery_conf_path, 0o600)

        return {
            "status": "ok",
            "message": "PITR restore files written. To use: include 'include_if_exists = blackbox_recovery.conf' in postgresql.conf, then restart PostgreSQL.",
            "recovery_signal": recovery_signal_path,
            "recovery_conf": recovery_conf_path,
            "wal_archive": WAL_ARCHIVE_DIR,
            "wal_file_count": wal_count,
            "target_time": target_time,
            "target_xid": target_xid,
        }
    except PermissionError as e:
        return {
            "status": "error",
            "message": f"Permission denied writing to {data_dir}: {e}. Run as postgres user or use --dry-run.",
        }
    except Exception as e:
        return {
            "status": "error",
            "message": f"Failed to write restore files: {e}",
        }


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="PITR restore for Blackbox BOM PostgreSQL")
    parser.add_argument(
        "--target-time", help="Recovery target timestamp (e.g. '2026-06-17 12:00:00 UTC')"
    )
    parser.add_argument("--target-xid", help="Recovery target transaction ID")
    parser.add_argument("--data-dir", default=PG_DATA_DIR, help="PostgreSQL data directory")
    parser.add_argument("--dry-run", action="store_true", help="Print config without writing files")
    parser.add_argument("--cleanup-wal", action="store_true", help="Clean up old WAL archive files")
    parser.add_argument(
        "--keep-days", type=int, default=7, help="Days of WAL archives to keep (default: 7)"
    )
    args = parser.parse_args()

    if args.cleanup_wal:
        result = cleanup_wal_archive(
            WAL_ARCHIVE_DIR, keep_days=args.keep_days, dry_run=args.dry_run
        )
        print(f"Status: {result['status']}")
        print(f"Removed: {result['removed_count']} files, freed {result['freed_bytes']} bytes")
        if result.get("removed_files"):
            print(f"Files: {', '.join(result['removed_files'][:20])}")
        sys.exit(0 if result["status"] == "ok" else 1)

    if not args.target_time and not args.target_xid:
        parser.print_help()
        print("\nError: Specify --target-time or --target-xid (or --cleanup-wal)")
        sys.exit(1)

    result = write_restore_files(
        target_time=args.target_time,
        target_xid=args.target_xid,
        data_dir=args.data_dir,
        dry_run=args.dry_run,
    )
    print(f"Status: {result['status']}")
    print(f"Message: {result['message']}")
    if "recovery_conf" in result and args.dry_run:
        print("\n--- Recovery config ---")
        print(result["recovery_conf"])
    sys.exit(0 if result["status"] in ("ok", "dry_run") else 1)
