// Sample BOM data — generic placeholder parts in a multi-level assembly
// Structure mirrors what a "Project ATLAS" mainframe might look like
window.BOM_DATA = {
  project: {
    code: "ATL-MFR-A",
    name: "Mainframe Assembly",
    rev: "C",
    version: "v3.2.0",
    status: "Released",
    owner: "E. Chen",
    updated: "2026-05-12",
  },
  rollup: {
    parts: 87,
    unique: 64,
    bomCost: 4218.40,
    lastCost: 4126.10,
    lead: 21,
    vendors: 14,
    countries: 6,
    risk: 3,
  },
  rows: [
    {
      id: "r1",
      pn: "ATL-MFR-A",
      name: "Mainframe Assembly",
      rev: "C",
      qty: 1, uom: "EA",
      category: "Assembly",
      vendor: "—",
      cost: 4218.40, lead: null, origin: "—",
      status: "Released",
      trend: null,
      assembly: true,
      children: [
        {
          id: "r1.1",
          pn: "ATL-MFR-CHS",
          name: "Chassis Subassembly",
          rev: "B",
          qty: 1, uom: "EA",
          category: "Assembly",
          vendor: "—",
          cost: 624.00, lead: null, origin: "—",
          status: "Released",
          assembly: true,
          children: [
            { id:"r1.1.1", pn:"MEC-PL-040A", name:"Side Panel, Anodized", rev:"D", qty:2, uom:"EA", category:"Mechanical", subCategory:"Enclosure", vendor:"Protolabs", manufacturer:"Blackbox Internal", cost:46.20, lead:7, origin:"US", status:"Released", trend:[42,43,44,45,44,46,46.2], material:"Aluminum 6061-T6", weight:320, dimensions:"200 × 120 × 3 mm", imageUrl:"https://placehold.co/120x120/oklch(0.55%200.08%2060)/white?text=Panel", customFields:{"Finish":"Type II Anodized, Black","Heat Rating":"85°C max"}, tags:["enclosure","custom"], compliance:["RoHS"], freight:4.20, tax:8.40, landedCost:58.80, countryHistory:[{country:"US", date:"2025-11", reason:"Initial sourcing"}], vendorPrices:[{vendor:"Protolabs", cost:46.20, lead:7, moq:1},{vendor:"Xometry", cost:52.00, lead:10, moq:5}], cadUrl:"cad/ATLAS/Mainframe/MEC-PL-040A.step" },
            { id:"r1.1.2", pn:"MEC-PL-041A", name:"Top Plate, Vented", rev:"B", qty:1, uom:"EA", category:"Mechanical", subCategory:"Enclosure", vendor:"Xometry", manufacturer:"Blackbox Internal", cost:58.90, lead:9, origin:"US", status:"Released", trend:[60,60,59,58,58,59,58.9], material:"Aluminum 6061-T6", weight:245, dimensions:"200 × 120 × 2.5 mm", tags:["enclosure","vented"], compliance:["RoHS"], freight:5.20, tax:10.80, landedCost:74.90, countryHistory:[{country:"US", date:"2025-10", reason:"Initial sourcing"}], vendorPrices:[{vendor:"Xometry", cost:58.90, lead:9, moq:1},{vendor:"Protolabs", cost:62.00, lead:7, moq:1}], cadUrl:"cad/ATLAS/Mainframe/MEC-PL-041A.step" },
            { id:"r1.1.3", pn:"MEC-BR-012", name:"Mounting Bracket, L-form", rev:"A", qty:4, uom:"EA", category:"Mechanical", subCategory:"Bracket", vendor:"Protolabs", manufacturer:"Blackbox Internal", cost:8.40, lead:7, origin:"US", status:"Released", trend:[7.8,8,8.1,8.3,8.4,8.5,8.4], material:"Steel A2-70", weight:45, dimensions:"40 × 30 × 4 mm", vendorPrices:[{vendor:"Protolabs", cost:8.40, lead:7, moq:1},{vendor:"Xometry", cost:9.20, lead:10, moq:5}], cadUrl:"cad/ATLAS/Mainframe/MEC-BR-012.step" },
            { id:"r1.1.4", pn:"HW-FAS-M3-08", name:"Screw, M3×8 Socket Head", rev:"—", qty:24, uom:"EA", category:"Hardware", subCategory:"Fastener", vendor:"McMaster", manufacturer:"McMaster-Carr", cost:0.08, lead:2, origin:"CN", status:"Released", trend:[0.08,0.08,0.08,0.08,0.08,0.08,0.08], barcode:"8901234567890", material:"Stainless Steel A2", weight:1.2, dimensions:"M3 × 8 mm", vendorPrices:[{vendor:"McMaster", cost:0.08, lead:2, moq:100},{vendor:"Mouser", cost:0.12, lead:5, moq:50}] },
            { id:"r1.1.5", pn:"HW-NUT-M3", name:"Nut, M3 Locking", rev:"—", qty:24, uom:"EA", category:"Hardware", subCategory:"Fastener", vendor:"McMaster", manufacturer:"McMaster-Carr", cost:0.04, lead:2, origin:"CN", status:"Released", trend:[0.04,0.04,0.04,0.04,0.04,0.04,0.04], barcode:"8901234567891", material:"Stainless Steel A2", weight:0.6, dimensions:"M3 × 2.4 mm" },
          ],
        },
        {
          id: "r1.2",
          pn: "ATL-MFR-PWR",
          name: "Power Subsystem",
          rev: "C",
          qty: 1, uom: "EA",
          category: "Assembly",
          vendor: "—",
          cost: 1284.20, lead: null, origin: "—",
          status: "Released",
          assembly: true,
          children: [
            { id:"r1.2.1", pn:"EL-PSU-240W", name:"Power Supply, 240W ATX", rev:"E", qty:1, uom:"EA", category:"Electrical", subCategory:"Power Supply", vendor:"Mean Well", manufacturer:"Mean Well", cost:84.00, lead:21, origin:"TW", status:"Released", trend:[78,79,81,82,83,84,84], material:"Aluminum/PCB", weight:680, dimensions:"150 × 86 × 65 mm", imageUrl:"https://placehold.co/120x120/oklch(0.55%200.13%20240)/white?text=PSU", tags:["power","psu","critical"], compliance:["RoHS","CE","UL"], freight:12.00, tax:15.40, landedCost:111.40, countryHistory:[{country:"TW", date:"2025-06", reason:"Initial"},{country:"TW", date:"2026-01", reason:"Price renegotiation"}], vendorPrices:[{vendor:"Mean Well", cost:84.00, lead:21, moq:50},{vendor:"Delta Electronics", cost:92.50, lead:28, moq:100},{vendor:"TDK-Lambda", cost:78.00, lead:35, moq:200}] },
            { id:"r1.2.2", pn:"EL-BAT-LI-18650", name:"Cell, Li-Ion 18650 3500mAh", rev:"B", qty:12, uom:"EA", category:"Electrical", subCategory:"Battery", vendor:"Panasonic", manufacturer:"Panasonic", cost:8.20, lead:28, origin:"JP", status:"Review", trend:[7.5,7.6,7.8,8.0,8.1,8.2,8.2], barcode:"4988600248173", material:"Lithium-Ion", weight:47, dimensions:"18 × 65 mm (cylindrical)", tags:["battery","cell","long-lead"], compliance:["RoHS","UN38.3"], freight:0.60, tax:1.50, landedCost:10.30, countryHistory:[{country:"JP", date:"2025-07", reason:"Initial"}], vendorPrices:[{vendor:"Panasonic", cost:8.20, lead:28, moq:100},{vendor:"Samsung SDI", cost:7.80, lead:35, moq:200},{vendor:"LG Chem", cost:9.00, lead:21, moq:150}] },
            { id:"r1.2.3", pn:"EL-BMS-12S", name:"BMS Board, 12S 60A", rev:"A", qty:1, uom:"EA", category:"Electrical", subCategory:"BMS", vendor:"Daly", manufacturer:"Daly", cost:64.00, lead:35, origin:"CN", status:"Released", trend:[60,61,62,63,64,64,64], material:"FR4/Components", weight:32, dimensions:"100 × 60 × 12 mm", tags:["bms","battery","critical"], compliance:["RoHS","CE"], freight:4.80, tax:11.70, landedCost:80.50, countryHistory:[{country:"CN", date:"2025-08", reason:"Initial"}], vendorPrices:[{vendor:"Daly", cost:64.00, lead:35, moq:10},{vendor:"JK BMS", cost:72.00, lead:21, moq:25}] },
            { id:"r1.2.4", pn:"EL-FAN-92", name:"Fan, 92mm PWM", rev:"C", qty:2, uom:"EA", category:"Electrical", subCategory:"Fan", vendor:"Noctua", manufacturer:"Noctua", cost:28.00, lead:14, origin:"AT", status:"Released", trend:[26,27,27,28,28,28,28], material:"Plastic/Steel", weight:92, dimensions:"92 × 92 × 25 mm", tags:["fan","cooling","active"], compliance:["RoHS","CE"], freight:2.10, tax:5.20, landedCost:35.30, vendorPrices:[{vendor:"Noctua", cost:28.00, lead:14, moq:10},{vendor:"Arctic", cost:18.00, lead:10, moq:20}] },
            { id:"r1.2.5", pn:"CB-PWR-AWG14", name:"Wire, 14AWG Silicone, RED", rev:"—", qty:2.4, uom:"M", category:"Cable", subCategory:"Power Wire", vendor:"BNTECHGO", manufacturer:"BNTECHGO", cost:1.80, lead:5, origin:"US", status:"Released", trend:[1.6,1.7,1.7,1.8,1.8,1.8,1.8], material:"Tinned Copper/Silicone", weight:14, dimensions:"14 AWG × 2.08 mm²", vendorPrices:[{vendor:"BNTECHGO", cost:1.80, lead:5, moq:10},{vendor:"Remington", cost:2.00, lead:7, moq:25}] },
            { id:"r1.2.6", pn:"CB-PWR-AWG14B", name:"Wire, 14AWG Silicone, BLK", rev:"—", qty:2.4, uom:"M", category:"Cable", subCategory:"Power Wire", vendor:"BNTECHGO", manufacturer:"BNTECHGO", cost:1.80, lead:5, origin:"US", status:"Released", material:"Tinned Copper/Silicone", weight:14, dimensions:"14 AWG × 2.08 mm²" },
          ],
        },
        {
          id: "r1.3",
          pn: "ATL-MFR-CTL",
          name: "Control Subsystem",
          rev: "D",
          qty: 1, uom: "EA",
          category: "Assembly",
          vendor: "—",
          cost: 1842.40, lead: null, origin: "—",
          status: "Review",
          assembly: true,
          children: [
            { id:"r1.3.1", pn:"EL-MCU-STM32H7", name:"MCU Module, STM32H743", rev:"B", qty:1, uom:"EA", category:"Electrical", subCategory:"IC", vendor:"STMicro", manufacturer:"STMicroelectronics", cost:18.40, lead:42, origin:"FR", status:"Released", trend:[14,15,16,17,18,18.4,18.4], barcode:"8901234567892", material:"Silicon/FR4", weight:5, dimensions:"14 × 14 mm (LQFP-100)", imageUrl:"https://placehold.co/120x120/oklch(0.55%200.13%20240)/white?text=MCU", customFields:{"Core":"ARM Cortex-M7 @ 480 MHz","Flash":"2 MB"}, tags:["mcu","active","long-lead"], compliance:["RoHS","REACH"], freight:1.20, tax:3.40, landedCost:23.00, countryHistory:[{country:"FR", date:"2025-03", reason:"Initial"},{country:"FR", date:"2026-02", reason:"Rev B upgrade"}], vendorPrices:[{vendor:"STMicro", cost:18.40, lead:42, moq:250},{vendor:"Mouser", cost:19.50, lead:14, moq:1},{vendor:"Digi-Key", cost:19.80, lead:10, moq:1}] },
            { id:"r1.3.2", pn:"EL-PCB-MAIN-R3", name:"Main PCB, R3 (4-layer)", rev:"C", qty:1, uom:"EA", category:"Electrical", subCategory:"PCB", vendor:"JLCPCB", manufacturer:"JLCPCB", cost:62.00, lead:14, origin:"CN", status:"Review", trend:[58,59,60,61,62,62,62], material:"FR4", weight:85, dimensions:"120 × 80 × 1.6 mm", tags:["pcb","main","4-layer"], compliance:["RoHS","UL"], freight:4.20, tax:11.40, landedCost:77.60, countryHistory:[{country:"CN", date:"2026-01", reason:"Initial proto"},{country:"CN", date:"2026-04", reason:"R3 revision"}], vendorPrices:[{vendor:"JLCPCB", cost:62.00, lead:14, moq:5},{vendor:"PCBWay", cost:58.00, lead:18, moq:10},{vendor:"Advanced Circuits", cost:85.00, lead:10, moq:20}] },
            { id:"r1.3.3", pn:"EL-MEM-DDR4-8G", name:"Memory, DDR4 8GB SODIMM", rev:"A", qty:2, uom:"EA", category:"Electrical", subCategory:"Memory", vendor:"Crucial", manufacturer:"Crucial", cost:32.50, lead:10, origin:"US", status:"Released", trend:[28,29,30,31,32,32.5,32.5], barcode:"4988600248174", material:"Silicon/FR4", weight:8, dimensions:"67.6 × 30 × 3.7 mm", tags:["memory","ddr4","sodimm"], compliance:["RoHS"], freight:2.40, tax:6.00, landedCost:40.90, vendorPrices:[{vendor:"Crucial", cost:32.50, lead:10, moq:1},{vendor:"Kingston", cost:34.00, lead:7, moq:1},{vendor:"Samsung", cost:36.00, lead:14, moq:50}] },
            { id:"r1.3.4", pn:"EL-CAM-IMX477", name:"Image Sensor Module, IMX477", rev:"B", qty:1, uom:"EA", category:"Optical", subCategory:"Camera", vendor:"Arducam", manufacturer:"Sony", cost:48.00, lead:18, origin:"CN", status:"Released", trend:[44,45,46,47,48,48,48], barcode:"4988600248175", material:"Glass/Silicon/FR4", weight:12, dimensions:"25 × 25 × 8 mm", imageUrl:"https://placehold.co/120x120/oklch(0.55%200.13%20320)/white?text=CAM", tags:["camera","sensor","optical"], compliance:["RoHS"], freight:3.60, tax:8.80, landedCost:60.40, countryHistory:[{country:"CN", date:"2025-09", reason:"Initial"}], vendorPrices:[{vendor:"Arducam", cost:48.00, lead:18, moq:5},{vendor:"Raspberry Pi", cost:52.00, lead:14, moq:10}] },
            { id:"r1.3.5", pn:"OPT-LNS-25MM", name:"Lens Assembly, 25mm f/1.8", rev:"A", qty:1, uom:"EA", category:"Optical", subCategory:"Lens", vendor:"Edmund Optics", manufacturer:"Edmund Optics", cost:189.00, lead:21, origin:"US", status:"Approved", trend:[180,182,185,187,188,189,189], barcode:"8901234567893", material:"Glass/Aluminum", weight:45, dimensions:"Ø30 × 28 mm", tags:["lens","optical","critical"], compliance:["RoHS"], freight:14.20, tax:34.80, landedCost:238.00, countryHistory:[{country:"US", date:"2025-12", reason:"Initial"}], vendorPrices:[{vendor:"Edmund Optics", cost:189.00, lead:21, moq:1},{vendor:"Thorlabs", cost:175.00, lead:14, moq:1}] },
            { id:"r1.3.6", pn:"CB-USB-C-30CM", name:"Cable, USB-C 30cm Internal", rev:"—", qty:1, uom:"EA", category:"Cable", subCategory:"Data Cable", vendor:"Tripp Lite", manufacturer:"Tripp Lite", cost:6.20, lead:7, origin:"CN", status:"Released", material:"TPE/Copper", weight:18, dimensions:"300 mm length" },
            { id:"r1.3.7", pn:"CB-FFC-40P-100", name:"Cable, FFC 40-pin 100mm", rev:"—", qty:2, uom:"EA", category:"Cable", subCategory:"Data Cable", vendor:"Molex", manufacturer:"Molex", cost:2.40, lead:14, origin:"US", status:"Released", material:"Polyimide/Copper", weight:3, dimensions:"100 × 10 × 0.3 mm", vendorPrices:[{vendor:"Molex", cost:2.40, lead:14, moq:100},{vendor:"TE Connectivity", cost:2.80, lead:10, moq:50}] },
          ],
        },
        {
          id: "r1.4",
          pn: "ATL-MFR-IO",
          name: "I/O Module",
          rev: "A",
          qty: 1, uom: "EA",
          category: "Assembly",
          vendor: "—",
          cost: 467.80, lead: null, origin: "—",
          status: "Draft",
          assembly: true,
          children: [
            { id:"r1.4.1", pn:"EL-CON-RJ45", name:"Connector, RJ45 Shielded", rev:"A", qty:2, uom:"EA", category:"Electrical", subCategory:"Connector", vendor:"Amphenol", manufacturer:"Amphenol", cost:1.80, lead:9, origin:"US", status:"Draft", barcode:"8901234567894", material:"Thermoplastic/Copper", weight:8, dimensions:"16 × 14 × 12 mm", vendorPrices:[{vendor:"Amphenol", cost:1.80, lead:9, moq:50},{vendor:"TE Connectivity", cost:2.10, lead:7, moq:100}] },
            { id:"r1.4.2", pn:"EL-CON-USBC", name:"Connector, USB-C Receptacle", rev:"B", qty:2, uom:"EA", category:"Electrical", subCategory:"Connector", vendor:"Hirose", manufacturer:"Hirose", cost:1.20, lead:14, origin:"JP", status:"Draft", barcode:"8901234567895", material:"Stainless Steel/Plastic", weight:3, dimensions:"8.3 × 2.5 × 6.5 mm", vendorPrices:[{vendor:"Hirose", cost:1.20, lead:14, moq:50},{vendor:"Amphenol", cost:1.40, lead:9, moq:100}] },
            { id:"r1.4.3", pn:"EL-IND-LED-3MM", name:"LED, 3mm Diffused RGB", rev:"—", qty:6, uom:"EA", category:"Electrical", subCategory:"Indicator", vendor:"Kingbright", manufacturer:"Kingbright", cost:0.40, lead:7, origin:"TW", status:"Draft", material:"Epoxy/Silicon", weight:0.4, dimensions:"Ø3 × 5 mm", vendorPrices:[{vendor:"Kingbright", cost:0.40, lead:7, moq:100},{vendor:"Lite-On", cost:0.35, lead:14, moq:200}] },
          ],
        },
      ],
    },
  ],

  vendors: [
    { id: "v1", name: "Mean Well", country: "TW", lead: 21, rating: 4.6, moq: 50, parts: 8, terms:"Net 30", risk:"Low", preferred: true },
    { id: "v2", name: "Protolabs", country: "US", lead: 7, rating: 4.4, moq: 1, parts: 14, terms:"Net 15", risk:"Low", preferred: true },
    { id: "v3", name: "McMaster", country: "US", lead: 2, rating: 4.9, moq: 1, parts: 22, terms:"Net 30", risk:"Low", preferred: true },
    { id: "v4", name: "JLCPCB", country: "CN", lead: 14, rating: 4.2, moq: 5, parts: 6, terms:"Prepaid", risk:"Med", preferred: false },
    { id: "v5", name: "Edmund Optics", country: "US", lead: 21, rating: 4.5, moq: 1, parts: 3, terms:"Net 30", risk:"Low", preferred: true },
    { id: "v6", name: "STMicro", country: "FR", lead: 42, rating: 4.0, moq: 250, parts: 4, terms:"Net 60", risk:"Med", preferred: false },
    { id: "v7", name: "Daly", country: "CN", lead: 35, rating: 3.7, moq: 10, parts: 2, terms:"Prepaid", risk:"High", preferred: false },
    { id: "v8", name: "Panasonic", country: "JP", lead: 28, rating: 4.7, moq: 100, parts: 5, terms:"Net 45", risk:"Low", preferred: true },
    { id: "v9", name: "Noctua", country: "AT", lead: 14, rating: 4.8, moq: 10, parts: 3, terms:"Net 30", risk:"Low", preferred: true },
    { id: "v10", name: "Xometry", country: "US", lead: 9, rating: 4.3, moq: 1, parts: 5, terms:"Net 30", risk:"Low", preferred: false },
    { id: "v11", name: "Crucial", country: "US", lead: 10, rating: 4.6, moq: 1, parts: 2, terms:"Net 15", risk:"Low", preferred: true },
    { id: "v12", name: "Arducam", country: "CN", lead: 18, rating: 4.1, moq: 5, parts: 2, terms:"Prepaid", risk:"Med", preferred: false },
    { id: "v13", name: "Molex", country: "US", lead: 14, rating: 4.5, moq: 100, parts: 4, terms:"Net 30", risk:"Low", preferred: false },
    { id: "v14", name: "Amphenol", country: "US", lead: 9, rating: 4.6, moq: 50, parts: 5, terms:"Net 30", risk:"Low", preferred: true },
  ],

  diff: {
    a: { ver:"v3.1.4", date:"2026-04-28", author:"M. Park" },
    b: { ver:"v3.2.0", date:"2026-05-12", author:"E. Chen" },
    changes: [
      { kind:"added", pn:"EL-MEM-DDR4-8G", desc:"Memory, DDR4 8GB SODIMM × 2", side:"b" },
      { kind:"removed", pn:"EL-MEM-DDR3-4G", desc:"Memory, DDR3 4GB SODIMM × 2", side:"a" },
      { kind:"changed", pn:"EL-MCU-STM32H7", desc:"Rev A → Rev B (errata fix)", side:"both" },
      { kind:"changed", pn:"EL-PSU-240W", desc:"Vendor: Delta → Mean Well; cost ₹6,142 → ₹6,972", side:"both" },
      { kind:"added", pn:"OPT-LNS-25MM", desc:"Lens Assembly, 25mm f/1.8", side:"b" },
      { kind:"changed", pn:"EL-PCB-MAIN-R3", desc:"R2 → R3 (4-layer); cost ₹3,984 → ₹5,146", side:"both" },
      { kind:"unchanged", pn:"HW-FAS-M3-08", desc:"Screw, M3×8 Socket Head (24)" },
      { kind:"unchanged", pn:"MEC-PL-040A", desc:"Side Panel, Anodized (2)" },
      { kind:"removed", pn:"EL-FAN-80", desc:"Fan, 80mm Sleeve", side:"a" },
      { kind:"added", pn:"EL-FAN-92", desc:"Fan, 92mm PWM × 2", side:"b" },
    ],
  },

  procurement: {
    "Not Ordered": [
      { pn:"EL-CON-RJ45", name:"Connector, RJ45", qty:200, vendor:"Amphenol", eta:"—" },
      { pn:"EL-CON-USBC", name:"Connector, USB-C", qty:200, vendor:"Hirose", eta:"—" },
    ],
    "RFQ Sent": [
      { pn:"EL-BMS-12S", name:"BMS Board, 12S 60A", qty:25, vendor:"Daly", eta:"—" },
      { pn:"EL-PCB-MAIN-R3", name:"Main PCB R3", qty:50, vendor:"JLCPCB", eta:"05-29" },
    ],
    "Ordered": [
      { pn:"EL-PSU-240W", name:"Power Supply 240W", qty:25, vendor:"Mean Well", eta:"06-04", attachments:["PO_PSU_240W.pdf","MeanWell_quote.pdf"] },
      { pn:"EL-MCU-STM32H7", name:"MCU STM32H743", qty:50, vendor:"STMicro", eta:"06-18", attachments:["STM32H7_Invoice.pdf"] },
      { pn:"OPT-LNS-25MM", name:"Lens 25mm f/1.8", qty:25, vendor:"Edmund Optics", eta:"06-02" },
    ],
    "In Transit": [
      { pn:"EL-MEM-DDR4-8G", name:"DDR4 8GB SODIMM", qty:50, vendor:"Crucial", eta:"05-27" },
      { pn:"HW-FAS-M3-08", name:"Screw, M3×8", qty:1000, vendor:"McMaster", eta:"05-26", attachments:["M3x8_Shipping.pdf"] },
      { pn:"EL-FAN-92", name:"Fan, 92mm PWM", qty:50, vendor:"Noctua", eta:"05-30" },
    ],
    "Received": [
      { pn:"MEC-PL-040A", name:"Side Panel, Anodized", qty:50, vendor:"Protolabs", eta:"✓" },
      { pn:"MEC-PL-041A", name:"Top Plate, Vented", qty:25, vendor:"Xometry", eta:"✓" },
      { pn:"EL-BAT-LI-18650", name:"Li-Ion Cell", qty:300, vendor:"Panasonic", eta:"✓" },
      { pn:"CB-PWR-AWG14", name:"Wire 14AWG", qty:50, vendor:"BNTECHGO", eta:"✓" },
    ],
    "Under Review": [
      { pn:"EL-CAP-22UF-50V", name:"MLCC 22µF 50V", qty:500, vendor:"Murata", eta:"06-15" },
      { pn:"EL-CON-RJ45", name:"Connector, RJ45", qty:200, vendor:"Amphenol", eta:"—" },
    ],
    "Quality Check": [
      { pn:"EL-PSU-240W", name:"Power Supply 240W", qty:25, vendor:"Mean Well", eta:"✓", qc: "pending" },
      { pn:"OPT-LNS-25MM", name:"Lens 25mm f/1.8", qty:25, vendor:"Edmund Optics", eta:"✓", qc: "passed" },
    ],
    "Approved": [
      { pn:"HW-FAS-M3-08", name:"Screw, M3×8", qty:1000, vendor:"McMaster", eta:"✓" },
    ],
    "Rejected": [
      { pn:"EL-FAN-80", name:"Fan, 80mm Sleeve", qty:10, vendor:"Generic", eta:"—", reason: "Wrong specification" },
    ],
    "Closed": [
      { pn:"MEC-PL-040A", name:"Side Panel, Anodized", qty:50, vendor:"Protolabs", eta:"✓", closed: "2026-05-20" },
      { pn:"EL-BAT-LI-18650", name:"Li-Ion Cell", qty:300, vendor:"Panasonic", eta:"✓", closed: "2026-05-18" },
    ],
  },

  activity: [
    { who:"E. Chen", init:"EC", color:"", time:"12 min", action:"changed", obj:"EL-MCU-STM32H7", note:"Bumped to Rev B per errata ES0392.", quote:"Field stress tests passed — moving the H743 from Rev A to Rev B fixes the I2C wakeup bug." },
    { who:"M. Park", init:"MP", color:"user-2", time:"54 min", action:"requested approval on", obj:"ATL-MFR-CTL Rev D" },
    { who:"R. Sato", init:"RS", color:"user-3", time:"2 hr", action:"commented on", obj:"EL-PCB-MAIN-R3", quote:"JLCPCB lead time looks fine but we should keep a 100-board safety stock — 14d is tight for the August demo." },
    { who:"System", init:"⌬", color:"sys", time:"3 hr", action:"detected", obj:"duplicate part", note:"HW-FAS-M3-08 matches HW-SCR-M3X8 (95% similarity)." },
    { who:"K. Singh", init:"KS", color:"user-4", time:"5 hr", action:"approved purchase order", obj:"PO-2026-0481", note:"Mean Well — ₹1,74,300" },
    { who:"E. Chen", init:"EC", color:"", time:"yesterday", action:"released BOM", obj:"v3.2.0", note:"Mainframe Assembly Rev C — released." },
    { who:"M. Park", init:"MP", color:"user-2", time:"yesterday", action:"uploaded", obj:"H743_errata_ES0392.pdf", note:"3 fields auto-extracted; awaiting confirmation." },
    { who:"System", init:"⌬", color:"sys", time:"2 days", action:"flagged supply risk on", obj:"EL-BMS-12S", note:"Daly lead time increased 28 → 35 days." },
  ],

  docs: [
    { name:"H743_Datasheet_RevB.pdf", ext:"PDF", icon:"DS", size:"4.2 MB", tag:"Datasheet", updated:"05-12" },
    { name:"Mainframe_Assy_Drawing.dwg", ext:"DWG", icon:"⌗", size:"1.1 MB", tag:"Drawing", updated:"05-12" },
    { name:"PSU_Compliance_CE.pdf", ext:"PDF", icon:"§", size:"612 KB", tag:"Compliance", updated:"05-10" },
    { name:"BOM_v3.2.0.xlsx", ext:"XLSX", icon:"▦", size:"248 KB", tag:"BOM", updated:"05-12" },
    { name:"PSU_Quote_MeanWell.pdf", ext:"PDF", icon:"$", size:"118 KB", tag:"Quote", updated:"05-08" },
    { name:"PCB_R3_Gerbers.zip", ext:"ZIP", icon:"⎘", size:"3.4 MB", tag:"CAD", updated:"05-09" },
    { name:"Test_Report_Thermal.pdf", ext:"PDF", icon:"≡", size:"892 KB", tag:"Test", updated:"05-07" },
    { name:"Vendor_Eval_Daly.pdf", ext:"PDF", icon:"☑", size:"432 KB", tag:"Vendor", updated:"05-03" },
    { name:"IMX477_Specs.pdf", ext:"PDF", icon:"DS", size:"2.1 MB", tag:"Datasheet", updated:"04-28" },
    { name:"Chassis_3D.step", ext:"STEP", icon:"⬢", size:"8.7 MB", tag:"CAD", updated:"04-25" },
  ],
};
